SET AUTOCOMMIT ON;
DELETE FROM BUYERS WHERE USER_ID IN (SELECT USER_ID FROM USERS WHERE USERNAME='kanchinidhish' OR EMAIL='Kanchi@gmail.com');
DELETE FROM SELLERS WHERE USER_ID IN (SELECT USER_ID FROM USERS WHERE USERNAME='kanchinidhish' OR EMAIL='Kanchi@gmail.com');
DELETE FROM USERS WHERE USERNAME='kanchinidhish' OR EMAIL='Kanchi@gmail.com';
COMMIT;
EXIT;
