-- Delete old products and re-seed 20 complete products (10 per seller)
DELETE FROM products;

-- SEL_001 = Cipla Health (USR_SELLER1) - 10 products across different categories
INSERT INTO products (PRODUCT_ID, SELLER_ID, NAME, MANUFACTURER, COMPOSITION, CATEGORY, RETAIL_PRICE, SELLING_PRICE, WHOLESALE_PRICE, STOCK_QUANTITY, MIN_QUANTITY, MIN_WHOLESALE_QTY, MIN_ORDER_QTY, DESCRIPTION, IMAGE_URL, STATUS) VALUES
('CPROD001', 'SEL_001', 'Crocin Advance 500mg', 'GSK Pharmaceuticals', 'Paracetamol 500mg', 'Analgesics', 45.00, 38.00, 32.00, 5000, 1, 100, 1, 'Crocin Advance provides fast and effective relief from fever, headache and body ache. Each tablet contains Paracetamol 500mg. Suitable for adults and children above 6 years.', 'default_medicine.png', 'ACTIVE'),
('CPROD002', 'SEL_001', 'Augmentin 625mg', 'GSK Pharmaceuticals', 'Amoxicillin 500mg + Clavulanate 125mg', 'Antibiotics', 320.00, 285.00, 240.00, 2000, 1, 50, 1, 'Augmentin 625mg is a broad-spectrum antibiotic used for bacterial infections of the respiratory tract, ear, sinus, skin and urinary tract. Combination of Amoxicillin and Clavulanate Potassium.', 'default_medicine.png', 'ACTIVE'),
('CPROD003', 'SEL_001', 'Metformin 500mg', 'Cipla Ltd', 'Metformin Hydrochloride 500mg', 'Antidiabetic', 85.00, 72.00, 60.00, 8000, 1, 200, 1, 'Metformin 500mg is an oral antidiabetic medication used to control blood sugar levels in Type 2 Diabetes Mellitus. Works by reducing glucose absorption and improving insulin sensitivity.', 'default_medicine.png', 'ACTIVE'),
('CPROD004', 'SEL_001', 'Pantoprazole 40mg', 'Cipla Ltd', 'Pantoprazole Sodium 40mg', 'Gastroenterology', 120.00, 98.00, 78.00, 4000, 1, 100, 1, 'Pantoprazole 40mg is a Proton Pump Inhibitor used to treat acidity, GERD, and peptic ulcers. Effectively reduces stomach acid production. Take before meals for best results.', 'default_medicine.png', 'ACTIVE'),
('CPROD005', 'SEL_001', 'Atorvastatin 10mg', 'Cipla Ltd', 'Atorvastatin Calcium 10mg', 'Cardiology', 180.00, 155.00, 130.00, 3500, 1, 100, 1, 'Atorvastatin 10mg is a statin medication used to lower bad cholesterol (LDL) and triglycerides while raising good cholesterol (HDL). Prescribed for cardiovascular disease prevention.', 'default_medicine.png', 'ACTIVE'),
('CPROD006', 'SEL_001', 'Cetirizine 10mg', 'Cipla Ltd', 'Cetirizine Hydrochloride 10mg', 'Antihistamines', 35.00, 28.00, 22.00, 6000, 1, 200, 1, 'Cetirizine 10mg is a second-generation antihistamine used to relieve allergy symptoms including runny nose, sneezing, itchy eyes, and hives. Non-drowsy formula suitable for daytime use.', 'default_medicine.png', 'ACTIVE'),
('CPROD007', 'SEL_001', 'Azithromycin 500mg', 'Cipla Ltd', 'Azithromycin 500mg', 'Antibiotics', 215.00, 185.00, 155.00, 1500, 1, 50, 1, 'Azithromycin 500mg is a macrolide antibiotic used for respiratory infections, pneumonia, and chlamydia. Usually prescribed as a 3 or 5-day course. Take on empty stomach.', 'default_medicine.png', 'ACTIVE'),
('CPROD008', 'SEL_001', 'Amlodipine 5mg', 'Cipla Ltd', 'Amlodipine Besylate 5mg', 'Cardiology', 95.00, 78.00, 62.00, 4500, 1, 100, 1, 'Amlodipine 5mg is a calcium channel blocker used to treat hypertension (high blood pressure) and angina. Helps relax blood vessels allowing heart to pump more efficiently.', 'default_medicine.png', 'ACTIVE'),
('CPROD009', 'SEL_001', 'Vitamin D3 60000 IU', 'Cipla Ltd', 'Cholecalciferol 60000 IU', 'Vitamins & Supplements', 145.00, 120.00, 95.00, 7000, 1, 200, 1, 'Vitamin D3 60000 IU sachet for treating Vitamin D deficiency. Essential for bone health, immune function and calcium absorption. Dissolve in water or milk and consume weekly.', 'default_medicine.png', 'ACTIVE'),
('CPROD010', 'SEL_001', 'Dexamethasone 0.5mg', 'Cipla Ltd', 'Dexamethasone 0.5mg', 'Steroids', 68.00, 55.00, 44.00, 2500, 1, 50, 1, 'Dexamethasone 0.5mg is a corticosteroid used to reduce inflammation and suppress immune response. Used in allergic reactions, asthma, arthritis, and severe COVID-19 cases.', 'default_medicine.png', 'ACTIVE'),

-- SEL_002 = Sun Pharma (USR_SELLER2) - 10 products across different categories
('SPROD001', 'SEL_002', 'Ibuprofen 400mg', 'Sun Pharmaceutical', 'Ibuprofen 400mg', 'Analgesics', 42.00, 35.00, 28.00, 5500, 1, 100, 1, 'Ibuprofen 400mg is a non-steroidal anti-inflammatory drug (NSAID) providing relief from pain, fever, and inflammation. Effective for headache, toothache, menstrual cramps, and arthritis pain.', 'default_medicine.png', 'ACTIVE'),
('SPROD002', 'SEL_002', 'Ondansetron 4mg', 'Sun Pharmaceutical', 'Ondansetron Hydrochloride 4mg', 'Gastroenterology', 78.00, 65.00, 52.00, 3000, 1, 100, 1, 'Ondansetron 4mg is a serotonin 5-HT3 receptor antagonist used to prevent nausea and vomiting caused by chemotherapy, radiation therapy, and surgery. Fast dissolving tablet formulation.', 'default_medicine.png', 'ACTIVE'),
('SPROD003', 'SEL_002', 'Glimepiride 2mg', 'Sun Pharmaceutical', 'Glimepiride 2mg', 'Antidiabetic', 95.00, 80.00, 65.00, 4000, 1, 100, 1, 'Glimepiride 2mg is a sulfonylurea antidiabetic drug used to manage Type 2 Diabetes Mellitus. Stimulates pancreatic insulin secretion. Take with first meal of the day.', 'default_medicine.png', 'ACTIVE'),
('SPROD004', 'SEL_002', 'Levothyroxine 50mcg', 'Sun Pharmaceutical', 'Levothyroxine Sodium 50mcg', 'Thyroid', 88.00, 72.00, 58.00, 3500, 1, 100, 1, 'Levothyroxine 50mcg is a synthetic thyroid hormone used to treat hypothyroidism and thyroid cancer. Take on empty stomach 30-60 minutes before breakfast. Regular monitoring required.', 'default_medicine.png', 'ACTIVE'),
('SPROD005', 'SEL_002', 'Sertraline 50mg', 'Sun Pharmaceutical', 'Sertraline Hydrochloride 50mg', 'Psychiatry', 255.00, 215.00, 175.00, 2000, 1, 50, 1, 'Sertraline 50mg is an SSRI antidepressant used for Major Depressive Disorder, OCD, Panic Disorder, PTSD and Social Anxiety. Take at same time daily. Effects seen after 2-4 weeks.', 'default_medicine.png', 'ACTIVE'),
('SPROD006', 'SEL_002', 'Losartan 50mg', 'Sun Pharmaceutical', 'Losartan Potassium 50mg', 'Cardiology', 115.00, 95.00, 76.00, 4000, 1, 100, 1, 'Losartan 50mg is an ARB (Angiotensin II Receptor Blocker) used to treat hypertension and diabetic nephropathy. Helps relax blood vessels and protect kidneys in diabetic patients.', 'default_medicine.png', 'ACTIVE'),
('SPROD007', 'SEL_002', 'Montelukast 10mg', 'Sun Pharmaceutical', 'Montelukast Sodium 10mg', 'Respiratory', 195.00, 165.00, 132.00, 3000, 1, 100, 1, 'Montelukast 10mg is a leukotriene receptor antagonist used for prevention of asthma and relief of allergic rhinitis symptoms. Take in the evening. Not for acute asthma attacks.', 'default_medicine.png', 'ACTIVE'),
('SPROD008', 'SEL_002', 'Methylcobalamin 500mcg', 'Sun Pharmaceutical', 'Methylcobalamin 500mcg + Pyridoxine + Folic Acid', 'Vitamins & Supplements', 125.00, 105.00, 84.00, 6000, 1, 200, 1, 'Methylcobalamin 500mcg with Pyridoxine and Folic Acid for treatment of Vitamin B12 deficiency, diabetic neuropathy, and peripheral nerve damage. Supports nerve regeneration.', 'default_medicine.png', 'ACTIVE'),
('SPROD009', 'SEL_002', 'Fluconazole 150mg', 'Sun Pharmaceutical', 'Fluconazole 150mg', 'Antifungal', 88.00, 72.00, 58.00, 2500, 1, 50, 1, 'Fluconazole 150mg is an antifungal medication used to treat vaginal yeast infections, oral thrush, and fungal meningitis. Single dose for most vaginal infections. Take with or without food.', 'default_medicine.png', 'ACTIVE'),
('SPROD010', 'SEL_002', 'Cystone Ayurvedic', 'Himalaya Drug Company', 'Shilapushpa + Pasanabheda + Shilajeet', 'Ayurvedic', 195.00, 165.00, 132.00, 5000, 1, 100, 1, 'Cystone is an Ayurvedic formulation used for kidney stones, urinary tract infections, and to maintain urinary tract health. Contains natural herbs that dissolve kidney stones and prevent recurrence.', 'default_medicine.png', 'ACTIVE');
