SET FOREIGN_KEY_CHECKS = 0;

CREATE DATABASE IF NOT EXISTS carecart;
USE carecart;

-- 1. USERS
CREATE TABLE IF NOT EXISTS USERS (
  USER_ID VARCHAR(32) PRIMARY KEY,
  USERNAME VARCHAR(100) NOT NULL UNIQUE,
  PASSWORD_HASH VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(150),
  ROLE VARCHAR(32) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2. RETAILERS
CREATE TABLE IF NOT EXISTS RETAILERS (
  RETAILER_ID VARCHAR(32) PRIMARY KEY,
  USER_ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(150) NOT NULL,
  CONTACT VARCHAR(150),
  LOCATION VARCHAR(255),
  FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 3. CLIENTS
CREATE TABLE IF NOT EXISTS CLIENTS (
  CLIENT_ID VARCHAR(32) PRIMARY KEY,
  USER_ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(150) NOT NULL,
  CONTACT VARCHAR(150),
  LOCATION VARCHAR(255),
  FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 4. CUSTOMERS
CREATE TABLE IF NOT EXISTS CUSTOMERS (
  CUSTOMER_ID VARCHAR(32) PRIMARY KEY,
  USER_ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(150) NOT NULL,
  CONTACT VARCHAR(150),
  ADDRESS TEXT,
  FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 5. CONSULTANTS
CREATE TABLE IF NOT EXISTS CONSULTANTS (
  CONSULTANT_ID VARCHAR(32) PRIMARY KEY,
  USER_ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(150) NOT NULL,
  EXPERTISE VARCHAR(255),
  CONTACT VARCHAR(150),
  FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 6. PRODUCTS
CREATE TABLE IF NOT EXISTS PRODUCTS (
  PRODUCT_ID VARCHAR(32) PRIMARY KEY,
  NAME VARCHAR(150) NOT NULL,
  RETAILER_ID VARCHAR(32) DEFAULT NULL,
  PRICE DECIMAL(12,2) DEFAULT 0.00,
  QUANTITY INT DEFAULT 0,
  MIN_QUANTITY INT DEFAULT 0,
  DESCRIPTION VARCHAR(255),
  FOREIGN KEY (RETAILER_ID) REFERENCES RETAILERS(RETAILER_ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 7. CLIENT_PRODUCTS (client-curated catalog)
CREATE TABLE IF NOT EXISTS CLIENT_PRODUCTS (
  CLIENT_ID VARCHAR(32) NOT NULL,
  PRODUCT_ID VARCHAR(32) NOT NULL,
  PRICE DECIMAL(12,2) DEFAULT NULL,
  QUANTITY INT DEFAULT 0,
  PRIMARY KEY (CLIENT_ID, PRODUCT_ID),
  FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(CLIENT_ID) ON DELETE CASCADE,
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 8. GOODS_RECEIPTS
CREATE TABLE IF NOT EXISTS GOODS_RECEIPTS (
  RECEIPT_ID INT PRIMARY KEY,
  RETAILER_ID VARCHAR(32) DEFAULT NULL,
  PRODUCT_ID VARCHAR(32) NOT NULL,
  QUANTITY INT NOT NULL,
  RECEIPT_DATE DATE,
  DESCRIPTION VARCHAR(255),
  FOREIGN KEY (RETAILER_ID) REFERENCES RETAILERS(RETAILER_ID) ON DELETE SET NULL,
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 9. STOCK_MOVEMENTS (audit log)
CREATE TABLE IF NOT EXISTS STOCK_MOVEMENTS (
  MOVEMENT_ID INT PRIMARY KEY,
  PRODUCT_ID VARCHAR(32) NOT NULL,
  CHANGE_QTY INT NOT NULL,
  REASON VARCHAR(50),
  REFERENCE_ID VARCHAR(64),
  MOVED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  DESCRIPTION VARCHAR(255),
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 10. ORDERS (unified for B2C/B2B)
CREATE TABLE IF NOT EXISTS ORDERS (
  ORDER_ID VARCHAR(32) PRIMARY KEY,
  ORDER_TYPE VARCHAR(8) NOT NULL,
  CUSTOMER_ID VARCHAR(32),
  CLIENT_ID VARCHAR(32),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  TOTAL_AMOUNT DECIMAL(12,2) DEFAULT 0.00,
  STATUS VARCHAR(40) DEFAULT 'NEW',
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID) ON DELETE SET NULL,
  FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(CLIENT_ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 11. ORDER_ITEMS
CREATE TABLE IF NOT EXISTS ORDER_ITEMS (
  ITEM_ID INT AUTO_INCREMENT PRIMARY KEY,
  ORDER_ID VARCHAR(32) NOT NULL,
  PRODUCT_ID VARCHAR(32) NOT NULL,
  QUANTITY INT NOT NULL,
  PRICE DECIMAL(12,2) NOT NULL,
  FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID) ON DELETE CASCADE,
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 12. PAYMENTS
CREATE TABLE IF NOT EXISTS PAYMENTS (
  PAYMENT_ID VARCHAR(32) PRIMARY KEY,
  ORDER_ID VARCHAR(32),
  AMOUNT DECIMAL(12,2) NOT NULL,
  METHOD VARCHAR(50),
  STATUS VARCHAR(40) DEFAULT 'PENDING',
  PAID_AT TIMESTAMP NULL,
  FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 13. CONSULTANCY_ENGAGEMENTS
CREATE TABLE IF NOT EXISTS CONSULTANCY_ENGAGEMENTS (
  ENGAGEMENT_ID VARCHAR(32) PRIMARY KEY,
  CLIENT_ID VARCHAR(32) NOT NULL,
  CONSULTANT_ID VARCHAR(32) NOT NULL,
  START_DATE DATE,
  END_DATE DATE,
  FEE DECIMAL(12,2),
  DESCRIPTION VARCHAR(255),
  FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(CLIENT_ID) ON DELETE CASCADE,
  FOREIGN KEY (CONSULTANT_ID) REFERENCES CONSULTANTS(CONSULTANT_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 14. INVOICES
CREATE TABLE IF NOT EXISTS INVOICES (
  INVOICE_ID VARCHAR(32) PRIMARY KEY,
  ORDER_ID VARCHAR(32),
  AMOUNT DECIMAL(12,2) NOT NULL,
  ISSUE_DATE DATE,
  DUE_DATE DATE,
  STATUS VARCHAR(40) DEFAULT 'UNPAID',
  FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET FOREIGN_KEY_CHECKS = 1;

