-- Schema body (apply against existing `carecart` database)

CREATE TABLE USERS (
    USER_ID VARCHAR(20) PRIMARY KEY,
    USERNAME VARCHAR(30) NOT NULL UNIQUE,
    PASSWORD VARCHAR(50) NOT NULL,
    ROLE VARCHAR(20) CHECK (ROLE IN ('ADMIN','CLIENT','CUSTOMER','CONSULTANT','RETAILER')),
    STATUS VARCHAR(10) DEFAULT 'ACTIVE'
);

CREATE TABLE CLIENTS (
    CLIENT_ID INT(6) PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
    PHONE VARCHAR(20) NOT NULL,
    ADDRESS VARCHAR(150) NOT NULL,
    CITY VARCHAR(50) NOT NULL,
    COUNTRY VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(150)
);

CREATE TABLE CUSTOMERS (
    CUSTOMER_ID INT(6) PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
    PHONE VARCHAR(15) NOT NULL,
    CITY VARCHAR(30) NOT NULL,
    DESCRIPTION VARCHAR(100)
);

CREATE TABLE RETAILERS (
    RETAILER_ID VARCHAR(20) PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
    PHONE VARCHAR(15) NOT NULL,
    LOCATION VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(100)
);

CREATE TABLE PRODUCTS (
    PRODUCT_ID VARCHAR(20) PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    RETAILER_ID VARCHAR(20) NOT NULL,
    PRICE DECIMAL(10,2) CHECK (PRICE > 0),
    QUANTITY INT CHECK (QUANTITY >= 0),
    MIN_QUANTITY INT CHECK (MIN_QUANTITY >= 0),
    DESCRIPTION VARCHAR(150),
    CONSTRAINT FK_PRODUCT_RETAILER 
        FOREIGN KEY (RETAILER_ID)
        REFERENCES RETAILERS(RETAILER_ID)
);

CREATE TABLE CONSULTANTS (
    CONSULTANT_ID VARCHAR(20) PRIMARY KEY,
    USER_ID VARCHAR(20) NOT NULL UNIQUE,
    FULL_NAME VARCHAR(50) NOT NULL,
    SPECIALTY VARCHAR(50) NOT NULL,
    QUALIFICATION VARCHAR(100) NOT NULL,
    RATING DECIMAL(3,2) CHECK (RATING BETWEEN 0 AND 5),
    DESCRIPTION VARCHAR(150),
    CONSTRAINT FK_CONSULTANT_USER 
        FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
);

CREATE TABLE CONSULTANCY_ENGAGEMENTS (
    ENGAGEMENT_ID INT(8) PRIMARY KEY,
    CLIENT_ID INT(6) NOT NULL,
    CONSULTANT_ID VARCHAR(20) NOT NULL,
    TITLE VARCHAR(50) NOT NULL,
    START_TIME DATETIME NOT NULL,
    END_TIME DATETIME,
    FEE DECIMAL(10,2) CHECK (FEE >= 0),
    STATUS VARCHAR(20),
    DESCRIPTION VARCHAR(150),
    CONSTRAINT FK_ENG_CLIENT 
        FOREIGN KEY (CLIENT_ID)
        REFERENCES CLIENTS(CLIENT_ID),
    CONSTRAINT FK_ENG_CONSULTANT 
        FOREIGN KEY (CONSULTANT_ID)
        REFERENCES CONSULTANTS(CONSULTANT_ID),
    CHECK (END_TIME > START_TIME)
);

CREATE TABLE ENGAGEMENT_INVOICES (
    INVOICE_ID INT(6) PRIMARY KEY,
    ENGAGEMENT_ID INT(8) NOT NULL,
    AMOUNT DECIMAL(10,2) CHECK (AMOUNT >= 0),
    STATUS VARCHAR(20),
    DUE_DATE DATE NOT NULL,
    DESCRIPTION VARCHAR(100),
    CONSTRAINT FK_INVOICE_ENG 
        FOREIGN KEY (ENGAGEMENT_ID)
        REFERENCES CONSULTANCY_ENGAGEMENTS(ENGAGEMENT_ID)
);

CREATE TABLE GOODS_RECEIPTS (
    RECEIPT_ID INT(6) PRIMARY KEY,
    RETAILER_ID VARCHAR(20) NOT NULL,
    PRODUCT_ID VARCHAR(20) NOT NULL,
    QUANTITY INT CHECK (QUANTITY > 0),
    RECEIPT_DATE DATE NOT NULL,
    DESCRIPTION VARCHAR(100),
    FOREIGN KEY (RETAILER_ID) REFERENCES RETAILERS(RETAILER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

CREATE TABLE STOCK_MOVEMENTS (
    MOVEMENT_ID INT PRIMARY KEY,
    PRODUCT_ID VARCHAR(20) NOT NULL,
    CHANGE_QTY INT CHECK (CHANGE_QTY <> 0),
    REASON VARCHAR(20),
    REFERENCE_ID VARCHAR(20) NOT NULL,
    DATE DATE NOT NULL,
    DESCRIPTION VARCHAR(100),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

CREATE TABLE STOCK_ALERTS (
    ALERT_ID INT PRIMARY KEY,
    PRODUCT_ID VARCHAR(20) NOT NULL,
    ALERT_TYPE VARCHAR(20),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_DATE DATE NOT NULL,
    DESCRIPTION VARCHAR(100),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

CREATE TABLE SALES_ORDERS (
    ORDER_ID VARCHAR(20) PRIMARY KEY,
    CLIENT_ID INT(6) NOT NULL,
    PRODUCT_ID VARCHAR(20) NOT NULL,
    QUANTITY INT CHECK (QUANTITY > 0),
    TOTAL_AMOUNT DECIMAL(10,2) CHECK (TOTAL_AMOUNT >= 0),
    STATUS VARCHAR(20),
    DESCRIPTION VARCHAR(100),
    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(CLIENT_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

CREATE TABLE CUSTOMER_ORDERS (
    ORDER_ID VARCHAR(20) PRIMARY KEY,
    CUSTOMER_ID INT(6) NOT NULL,
    PRODUCT_ID VARCHAR(20) NOT NULL,
    QUANTITY INT CHECK (QUANTITY > 0),
    TOTAL_AMOUNT DECIMAL(10,2) CHECK (TOTAL_AMOUNT >= 0),
    STATUS VARCHAR(20),
    DESCRIPTION VARCHAR(100),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

CREATE TABLE PAYMENTS (
    PAYMENT_ID INT PRIMARY KEY,
    ORDER_ID VARCHAR(20) NOT NULL,
    AMOUNT DECIMAL(10,2) CHECK (AMOUNT >= 0),
    MODE VARCHAR(20),
    STATUS VARCHAR(20),
    DESCRIPTION VARCHAR(100),
    FOREIGN KEY (ORDER_ID) REFERENCES CUSTOMER_ORDERS(ORDER_ID)
);
