server.port=8081
server.servlet.context-path=/carecart

# Database connection will be picked up from .env if using a loader, 
# but for manual run, we can put defaults here:
# Institutional B2B Oracle Connection
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xepdb1
spring.datasource.username=system
spring.datasource.password=1234
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/carecart
