-- Buyer Orders Page: view orders, cancel a pending order
-- Page: /app/buyer/orders | Triggered by: page load, CANCEL ORDER button
-- Test: mysql -u root -pKartk@30 carecart < buyer_orders_cancel_order.sql

USE carecart;

-- READ: all orders for a logged-in buyer with product details
SELECT o.order_id, o.bundle_id, o.status, o.quantity, o.unit_price,
       o.total_amount, o.tax_amount, o.delivery_charge, o.grand_total,
       o.order_date, o.shipping_address,
       p.name AS product_name, p.image_url
FROM orders o
JOIN products p ON o.product_id = p.product_id
WHERE o.buyer_id = 'B-USR_BUYER1'
ORDER BY o.order_date DESC;

-- READ: check if order is cancellable (only PENDING orders can be cancelled)
SELECT order_id, status FROM orders
WHERE order_id = 'ORD_001' AND buyer_id = 'B-USR_BUYER1' AND status = 'PENDING';

-- UPDATE: cancel a pending order (calls sp_update_order_status in backend)
CALL sp_update_order_status('ORD_001', 'CANCELLED', 'BUYER', @result);
SELECT @result;

-- READ: verify stock was restored after cancel
SELECT product_id, stock_quantity FROM products WHERE product_id = 'CPROD001';

-- READ: verify wallet was restored after cancel
SELECT wallet_balance FROM buyers WHERE buyer_id = 'B-USR_BUYER1';

-- READ: status audit log generated by trigger after cancel
SELECT old_status, new_status, changed_by, log_time
FROM order_status_log WHERE order_id = 'ORD_001';

-- MANUAL TEST (rollback-safe for direct SQL, procedure handles its own transaction)
START TRANSACTION;
SELECT order_id, status FROM orders WHERE order_id = 'ORD_001';
UPDATE orders SET status = 'CANCELLED' WHERE order_id = 'ORD_001' AND status = 'PENDING';
SELECT status FROM orders WHERE order_id = 'ORD_001';
ROLLBACK;
